theme: jekyll-theme-minimal

title: DCC Licht
description: Digital Command Control (DCC)
logo: https://github.com/eurovibes/dcclicht/raw/master/images/dcclicht.png
show_downloads: true

github:
  zip_url: downloads/fabrication.zip
  tar_url: downloads/fabrication.tar.gz
